services:
  base:
    image: base:el7
    build: base-el7
    command: /usr/bin/true
  postgis_21_94:
    image: postgis:21_94
    depends_on:
    - postgis_21_94_db
  postgis_21_94_db:
    image: postgis:21_94
    build:
      context: image-postgis
      args:
        postgresql_version_full: '9.4'
        postgresql_version_abbr: '94'
        postgis_package_version_abbr: '2'
    command: /usr/sbin/init
    ports:
    - 5432:5432
    volumes:
    - pgdata94:/var/lib/pgdata/9.4/data
  postgis_24_94:
    image: postgis:24_94
    depends_on:
    - postgis_24_94_db
  postgis_24_94_db:
    image: postgis:24_94
    build:
      context: image-postgis
      args:
        postgresql_version_full: '9.4'
        postgresql_version_abbr: '94'
        postgis_package_version_abbr: '24'
    command: /usr/sbin/init
    ports:
    - 5432:5432
    volumes:
    - pgdata94:/var/lib/pgdata/9.4/data
  postgis_24_11:
    image: postgis:24_11
    depends_on:
    - postgis_24_11_db
  postgis_24_11_db:
    image: postgis:24_11
    build:
      context: image-postgis
      args:
        postgresql_version_full: '11'
        postgresql_version_abbr: '11'
        postgis_package_version_abbr: '24'
    command: /usr/sbin/init
    ports:
    - 5432:5432
    volumes:
    - pgdata11:/var/lib/pgdata/11/data
  postgis_33_11:
    image: postgis:33_11
    depends_on:
    - postgis_33_11_db
  postgis_33_11_db:
    image: postgis:33_11
    build:
      context: image-postgis
      args:
        postgresql_version_full: '11'
        postgresql_version_abbr: '11'
        postgis_package_version_abbr: '33'
    command: /usr/sbin/init
    ports:
    - 5432:5432
    volumes:
    - pgdata11:/var/lib/pgdata/11/data
  postgis_33_15:
    image: postgis:33_15
    depends_on:
    - postgis_33_15_db
  postgis_33_15_db:
    image: postgis:33_15
    build:
      context: image-postgis
      args:
        postgresql_version_full: '15'
        postgresql_version_abbr: '15'
        postgis_package_version_abbr: '33'
    command: /usr/sbin/init
    ports:
    - 5432:5432
    volumes:
    - pgdata15:/var/lib/pgdata/15/data
volumes:
  pgdata94:
  pgdata11:
  pgdata15:

